version: '3.8'

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    networks:
      - app-network
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: secret
    ports:
      - "8000:80" # maps localhost:8000 to container's Nginx port

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: nextjs-frontend
    container_name: nextjs-frontend
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - app
    environment:
      - NEXT_PUBLIC_API_URL=http://laravel-app/api
    ports:
      - "3000:3000" # maps localhost:3000 to Next.js port

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:

volumes:
  dbdata:
